### ISSUE TITLE
Link to Klarna documentation from the documentation home is broken

### ISSUE THREAD

**Issue by ksolberg** [vendrhub/vendr-documentation#59]
Link to Klarna documentation from the documentation home is broken.

**Comment by mattbrailsford** [comment]
Thanks @ksolberg 

That should be fixed now. It will just take a little while for the docs build server to re-deploy it.

Thanks for letting me know 👍

**Comment by ksolberg** [comment]
Still broken (404).

**Comment by mattbrailsford** [comment]
Doh! Looks like the docs build failed. I'm re-running it now to see if it'll deploy this time.

**Comment by mattbrailsford** [comment]
Ok that's fixed now, not erroring. Though it looks like that's one of the providers we haven't got docs for anyway yet, so unfortunately if you were looking for docs on this one, we are yet to write them 🤦
