### ISSUE TITLE
README: Gridsome prerequisite

### ISSUE THREAD

**Issue by UnitStack** [vendrhub/vendr-documentation#6]
ISSUE:

On the readme file for getting started with contributing to these documents, there is no mention of gridsome having to be installed before running. I have no experience with gridsome so if I have misunderstood do let me know, but the below is what worked for me.

I had to run
`yarn global add @gridsome/cli`

As without it, running `gridsome develop` fails.

FIX:
Add `yarn global add @gridsome/cli` into getting started step 4 above `gridsome develop`

Happy to do PR

**Comment by mattbrailsford** [comment]
Hey @UnitStack 

You are absolutely right, it must have missed that. Happy for you to submit a PR for sure.

Really appreciated 👍

**Comment by mattbrailsford** [comment]
PR #7 merged in. Thanks for reporting and submitting an update 👍
