### ISSUE TITLE
Custom order actions in backoffice

### ISSUE THREAD

**Issue by ksolberg** [vendrhub/vendr-documentation#60]
It would be nice if you could add custom actions in the actions box in the order view.

![custom-actions](https://user-images.githubusercontent.com/144644/103649360-9c232080-4f5e-11eb-96d5-6b0851657dc0.PNG)

**Comment by mattbrailsford** [comment]
Thanks for reporting @ksolberg but would you mind reporting it on the Vendr repo, not the docs repo? https://github.com/vendrhub/vendr

I would transfer it, but I don't seem to be able to select the Vendr repository to transfer the issue to.
