### ISSUE TITLE
Avoid horizontal scroll

### ISSUE THREAD

**Issue by bjarnef** [vendrhub/vendr-documentation#8]
On some of the pages the longer headings cause horizontal scroll in mobile, which push the menu button to the right, so it isn't visible at first sights.

I think it would be better to break word for these longer headings to avoid horizontal page scroll on mobile.

![Screenshot_20200425-154143_Chrome](https://user-images.githubusercontent.com/2919859/80302597-3cf3f600-87ab-11ea-8098-0df601b6ba2e.jpg)

![Screenshot_20200425-154152_Chrome](https://user-images.githubusercontent.com/2919859/80302604-44b39a80-87ab-11ea-80ca-231274660971.jpg)

**Comment by mattbrailsford** [comment]
Fixed. Headings now break if they are too long.
