### ISSUE TITLE
Incorrect license directory

### ISSUE THREAD

**Issue by bllteasolutionsdk** [vendrhub/vendr-documentation#84]
According to the documentation, the "umbraco\Data" directory will be scanned for valid licenses by default.

It appears that the actual directory is "umbraco\Licenses".

Umbraco 9/Vendr 2.0.3

**Comment by mattbrailsford** [comment]
Good spot. 

The ‘umbraco\Licenses’ directory was only recently added as a standard folder for licenses which prior to that update we used the Data folder. 

Will get this updated 👍🏻

**Comment by mattbrailsford** [comment]
This has been updated 👍
